import React from "react";
import { FiArrowRight, FiPlus } from "react-icons/fi";
import { BsBracesAsterisk, BsFillMenuButtonWideFill } from "react-icons/bs";

function BootUtility() {
  return (
    <div className="bootUtility">
      <section className="pb-md-5 mb-5 pad">
        <div className="col-lg-8 mb-5">
          <div
            className="masthead-followup-icon d-inline-block mb-3 me-2 p-3 px-4 rounded-3"
            style={{ backgroundColor: "#f8bab6" }}
          >
            <BsFillMenuButtonWideFill
              className="fs-3"
              style={{ color: "#ff1000" }}
            />
          </div>
          <FiPlus className="me-2 fs-3" />
          <div
            className="masthead-followup-icon d-inline-block mb-3 p-3 px-4 rounded-3"
            style={{ backgroundColor: "#bbf8f7" }}
          >
            <BsBracesAsterisk className="fs-3" style={{ color: "#00fffa" }} />
          </div>
          <h2 className="display-5 mb-3 fw-semibold lh-sm">
            Components, meet the Utility&nbsp;API
          </h2>
          <p className="lead fw-normal">
            New in Bootstrap 5, our utilities are now generated by our{" "}
            <a href="/">Utility API</a>. We built it as a feature-packed Sass
            map that can be quickly and easily customized. It's never been
            easier to add, remove, or modify any utility classes. Make utilities
            responsive, add pseudo-class variants, and give them custom names.
          </p>
        </div>
        <div className="row gx-md-5">
          <div className="col-lg-6">
            <h3 className="fw-semibold">Quickly customize components</h3>
            <p>
              Apply any of our included utility classes to our components to
              customize their appearance, like the navigation example below.
              There are hundreds of classes available—from{" "}
              <a href="/">positioning</a> and{" "}
              <a href="/">sizing</a> to{" "}
              <a href="/">colors</a> and{" "}
              <a href="/">effects</a>. Mix them with
              CSS variable overrides for even more control.
            </p>
            <div className="p-4 border rounded-3 mb-4">
              <ul className="nav nav-pills mb-4" id="pillNav" role="tablist">
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link active"
                    id="home-tab"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="true"
                  >
                    Home
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="profile-tab"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="false"
                  >
                    Profile
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="contact-tab"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="false"
                  >
                    Contact
                  </button>
                </li>
              </ul>
              <ul
                className="nav nav-pills nav-fill gap-2 p-1 small bg-primary rounded-5 shadow-sm"
                id="pillNav2"
                role="tablist"
              >
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link active rounded-5 bg-light text-primary"
                    id="home-tab2"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="true"
                  >
                    Home
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link rounded-5 text-light"
                    id="profile-tab2"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="false"
                  >
                    Profile
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link rounded-5 text-light"
                    id="contact-tab2"
                    data-bs-toggle="tab"
                    type="button"
                    role="tab"
                    aria-selected="false"
                  >
                    Contact
                  </button>
                </li>
              </ul>
            </div>
            <div className="highlight">
              <pre
                tabIndex={0}
                className="chroma border border-1 p-3 rounded rounded-3"
              >
                <code className="language-html" data-lang="html">
                  <span className="line">
                    {`<ul class="nav nav-pills nav-fill gap-2 p-1 small bg-primary rounded-5 shadow-sm" id="pillNav2" role="tablist" style="--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
  <li class="nav-item" role="presentation">
    <button class="nav-link active rounded-5" id="home-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="true">Home</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link rounded-5" id="profile-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Profile</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link rounded-5" id="contact-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Contact</button>
  </li>
</ul>`}
                  </span>
                </code>
              </pre>
            </div>
            <p className="d-flex justify-content-start mb-md-0 mt-4">
              <a
                href="/docs/5.3/examples#snippets"
                className="icon-link icon-link-hover fw-semibold"
              >
                Explore customized components
                <FiArrowRight className="mt-1" />
              </a>
            </p>
          </div>
          <div className="col-lg-6">
            <h3 className="fw-semibold">Create and extend utilities</h3>
            <p>
              Use Bootstrap's utility API to modify any of our included
              utilities or create your own custom utilities for any project.
              Import Bootstrap first, then use Sass map functions to modify,
              add, or remove utilities.
            </p>
            <div className="highlight">
              <pre
                tabIndex={0}
                className="chroma border border-1 p-3 rounded rounded-3"
              >
                {"                "}
                <code className="language-scss" data-lang="scss">
                  <span className="line">
                    {`
@import "bootstrap/scss/bootstrap";

$utilities: map-merge(
  $utilities,
  (
    "cursor": (
      property: cursor,
      class: cursor,
      responsive: true,
      values: auto pointer grab,
    )
  )
);`}
                  </span>
                </code>
              </pre>
            </div>
            <p className="d-flex justify-content-start mb-md-0 mt-4">
              <a
                href="/docs/5.3/utilities/api/"
                className="icon-link icon-link-hover fw-semibold mb-3"
              >
                Explore the utility API
                <FiArrowRight className="mt-1" />
              </a>
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default BootUtility;
